version: 2.1

jobs:
  sonar-scan:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.1.0

workflows:
  test-and-deploy:
    jobs:
      - sonar-scan
      - node/test
      - heroku/deploy-via-git:
          requires:
          - node/test
          filters:
            branches:
                only: main


