version: 2.1

jobs:
  build-docker-image:
    environment:
      IMAGE_NAME: bfamchon/my-repository/my-image
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  sonar-scan:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.1.0

workflows:
  build-main:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only: main
  test-and-deploy:
    jobs:
      - sonar-scan:
          context: Sonarcloud
      - node/test
      - heroku/deploy-via-git:
          requires:
          - node/test
          filters:
            branches:
                only: main


