version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: bfamchon/my-repository
    docker:
      - image: cimg/base:current

jobs:
  build-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
            - ./ansible
  publish-image:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  sonar-scan:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
  deploy-staging:
      docker:
        - image: ansible/ansible:ubuntu1604
      environment:
          ANSIBLE_HOST_KEY_CHECKING: "false"
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - add_ssh_keys:
            fingerprints:
              - "4f:73:b2:e2:15:94:7d:0c:52:e2:c8:63:be:3a:46:67"
        - run:
            name: Create vars folder
            command: "ls -al && ls -al /tmp/workspace && mkdir -p ansible/vars"
        - run:
            name: Set docker registry
            command: 'echo -e "---ndocker_token: $DOCKERHUB_PASS ndocker_user: $DOCKERHUB_USERNAME ndocker_registry: bfamchon/my-repository " > ansible/vars/docker_credentials.yml'
        - run:
            name: Install ansible
            command: python -m pip install pip==20.1.1 && python -m pip install ansible && python -m pip install jmespath
        - run:
            name: Deploy to staging
            command: ls -al && cd ansible && ls -al && cat vars/docker_credentials.yml && ansible-playbook -i staging deployment.yml
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.1.0

workflows:
  test-and-deploy:
    jobs:
      - sonar-scan:
          context: Sonarcloud
      - node/test
      - build-image:
          filters:
            branches:
              only: main
      - publish-image:
          context: Dockerhub
          filters:
            branches:
              only: main
          requires:
          - node/test
          - build-image
      - deploy-staging:
          context: Dockerhub
          filters:
              branches:
                only: main
          requires:
            - publish-image
      - heroku/deploy-via-git:
          requires:
          - node/test
          filters:
            branches:
                only: main


